export const ErrorCodes = {
  // 인증 관련
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // 회원 관련
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  MEMBER_ALREADY_EXISTS: 'MEMBER_ALREADY_EXISTS',

  // 평가 관련
  ASSESSMENT_NOT_FOUND: 'ASSESSMENT_NOT_FOUND',
  ASSESSMENT_DELETE_FORBIDDEN: 'ASSESSMENT_DELETE_FORBIDDEN',
  INITIAL_ASSESSMENT_ALREADY_EXISTS: 'INITIAL_ASSESSMENT_ALREADY_EXISTS',

  // 부상 관련
  INJURY_NOT_FOUND: 'INJURY_NOT_FOUND',

  // 검증 관련
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // 서버 관련
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

